### PR TITLE
Fixed: location Tricks and Treats in Twilight Highlands

### PR DESCRIPTION
**Pull request by JanGalek**
- Fixed: location Tricks and Treats in Twilight Highlands
- Fixed: Field photographer in westfall

### CODE REVIEW

**Comment by idiomatic** [comment]
The source-of-truth for AchievementLocations is the gigantic Google Sheets spreadsheet.  The `derive.coffee` script automatically (and consistently) converts the spreadsheet data into Lua.  The GitHub Actions Derive runs `derive.coffee` and commits the changes (see 12c3378505a6f0f02e98ce0a5f4fb477c7aa2f7c).

I translated your Lua into data, including rounding to 3 decimal places.

**Comment by JanGalek** [comment]
I want set position more close for minimap :)

**Comment by JanGalek** [comment]
@idiomatic so should I still send PR here ? :/

**Comment by idiomatic** [comment]
> I want set position more close for minimap :)

Let's compromise and go 4 decimal places.

**Comment by JanGalek** [comment]
so sorry that I don't work on Achievement updates, now is Halloween Ends event and I want finish it, but while I checking positions for locations - little compromise :)

**Comment by idiomatic** [comment]
> @idiomatic so should I still send PR here ? :/

Yes, though it is sub-optimal for both of us.  It does afford you the benefit of in-person testing, but it appears backwards to go Lua to spreadsheet, then spreadsheet to Lua.  In this case, it allowed me to compare the diffs!  (DIFFCEPTION)


The original plan was to have the add-on collect data, then to have add-on to add-on communication to collect player-contributed data.  The collector-mode for the add-on would be used by someone with spreadsheet access and spreadsheet talent.  I made it overly-complicated by adding cryptographic signing of messages and a peer-to-peer network.  In hindsight, a direct-communication protocol simplification and dumping stale uncollected (and likely redundant) data would have been easier.

The future options include:

1) add a change submission webform, or
2) add change submission GitHub Issue templates, or
3) handle change suggestions within Google Sheets (assuming Sheets has the feature), or
4) grant spreadsheet change access

These options are in increasing detail-orientation order.

Following up on #4.

**Comment by idiomatic** [comment]
> > I want set position more close for minimap :)
> 
> Let's compromise and go 4 decimal places.

Upgrading from 3 decimal places to 4 caused massive diff in 82d5ddd218d16ea1900be1af50adbb0d65133776.

**Pull request closed without merging**
